// SPDX-License-Identifier: MIT
pragma solidity >=0.8.24;

/* Autogenerated file. Do not edit manually. */

import { PlayerPosition, PlayerPositionData } from "./tables/PlayerPosition.sol";
import { CoinPosition } from "./tables/CoinPosition.sol";
import { PlayerCoins } from "./tables/PlayerCoins.sol";
